// Portfolio items for each service
export interface PortfolioItem {
  name: string;
  category: string;
  desc: string;
  stat?: string;
}

const servicePriority = [
  'brand-identity',
  'logo-design',
  'graphic-design',
  'social-media-management',
  'digital-marketing',
  'ui-ux-design',
  'website-development',
  'shopify-development',
  'seo',
  'custom-theme-development',
  'speed-optimization',
  'maintenance-support',
];

export const allServices = [
  {
    slug: 'logo-design',
    icon: '✺',
    title: 'Logo Design',
    short: 'Strong brand identity that customers remember and trust instantly.',
    hero: 'A forgettable or confusing logo costs you credibility from day one. We build brand systems customers remember.',
    desc: 'An unclear or generic logo damages perception before people even try your product. Customers remember brands through visuals, color palette, and tone — all working together. We research your audience, competitors, and positioning first, then create identity systems that communicate quality, specialization, and confidence across packaging, digital screens, and print materials.',
    features: ['3 unique logo concepts', 'Unlimited revisions until perfect', 'Full color + B&W versions', 'All file formats (AI, SVG, PNG, PDF)', 'Brand mark + wordmark variations', 'Social media profile versions', 'Favicon & app icon versions', 'Brand color palette included', 'Typography recommendations', 'Logo usage guidelines'],
    results: ['100% custom designs', '48hr first concepts', 'Lifetime ownership'],
    howItWorks: [
      { step: '01', title: 'Brand Discovery', desc: 'We learn about your business, values, audience, and competitors.' },
      { step: '02', title: '3 Unique Concepts', desc: 'You receive 3 distinct logo directions with mood boards.' },
      { step: '03', title: 'Refinement', desc: 'We refine your chosen concept until it\'s perfect.' },
      { step: '04', title: 'Final Delivery', desc: 'All file formats, variations, and guidelines delivered.' },
    ],
    categories: ['Gaming & Esports', 'Business & Corporate', 'Food & Restaurant', 'Fashion & Beauty', 'Tech & Startup', 'Sports & Fitness', 'Real Estate', 'Healthcare', 'Education', 'Music & Entertainment'],
    whyChoose: [
      { title: '100% Original', desc: 'No templates, no stock icons. Every element is designed from scratch for your brand.' },
      { title: 'Strategic Thinking', desc: 'We do more than make attractive logos. Every direction is designed around your business goals.' },
      { title: 'Unlimited Revisions', desc: 'We refine until you\'re completely satisfied. No extra charges.' },
    ],
    faqs: [
      { q: 'How many logo options do I get?', a: 'You receive 3 unique concepts. Then we refine your favorite with unlimited revisions.' },
      { q: 'What files will I receive?', a: 'AI, SVG, PNG (transparent), PDF, JPG in full color, black, white, and variations.' },
      { q: 'Can you redesign my existing logo?', a: 'Yes! We can modernize, refine, or completely reimagine your current logo.' },
      { q: 'How long does logo design take?', a: 'First concepts in 48-72 hours. Full project typically 5-7 days including revisions.' },
    ],
    portfolio: [
      { name: 'NexGen Gaming', category: 'Gaming & Esports', desc: 'Bold esports team logo with dynamic typography', stat: 'Gaming' },
      { name: 'Vertex Finance', category: 'Business & Corporate', desc: 'Minimalist mark for fintech startup', stat: 'Corporate' },
      { name: 'Spice Route', category: 'Food & Restaurant', desc: 'Elegant emblem for premium restaurant', stat: 'Restaurant' },
      { name: 'Luxe Attire', category: 'Fashion & Beauty', desc: 'Sophisticated wordmark for fashion brand', stat: 'Fashion' },
      { name: 'CodeStack', category: 'Tech & Startup', desc: 'Modern tech logo with clever symbol', stat: 'Tech' },
      { name: 'Iron Athletics', category: 'Sports & Fitness', desc: 'Powerful emblem for fitness brand', stat: 'Sports' },
      { name: 'Crown Properties', category: 'Real Estate', desc: 'Premium mark for luxury real estate', stat: 'Real Estate' },
      { name: 'MindCare', category: 'Healthcare', desc: 'Warm, trustworthy healthcare logo', stat: 'Healthcare' },
    ],
  },
  {
    slug: 'graphic-design',
    icon: '◈',
    title: 'Graphic Design',
    short: 'Compelling visuals that make your message unforgettable.',
    hero: 'Blended into feed, your competitors become interchangeable. Strong graphics help you stand out and stay remembered.',
    desc: 'Essential design language drives sales. Every post, brochure, presentation, and campaign should match your personality, voice, and values. Inconsistent design is affordable confusion. We create brand-consistent graphics that work across platforms, engage audiences, and communicate your competitive edge — each element designed to shift perception and encourage action.',
    features: ['Social media post designs', 'Story & reel templates', 'Banner & cover designs', 'Flyer & brochure design', 'Poster & signage', 'Business cards & stationery', 'Presentation design', 'Infographics', 'Email headers', 'Ad creatives (Meta, Google)'],
    results: ['24-48hr turnaround', 'Unlimited revisions', 'Source files included'],
    howItWorks: [
      { step: '01', title: 'Brief & Brand', desc: 'We understand your needs, brand guidelines, and target audience.' },
      { step: '02', title: 'Concept Design', desc: 'First drafts delivered within 24-48 hours.' },
      { step: '03', title: 'Revisions', desc: 'Unlimited revisions until you\'re 100% happy.' },
      { step: '04', title: 'Final Files', desc: 'All required formats are delivered, ready for print and optimized for digital use.' },
    ],
    categories: ['Social Media Graphics', 'Instagram Posts & Stories', 'Facebook & LinkedIn', 'YouTube Thumbnails', 'Flyers & Posters', 'Brochures & Catalogs', 'Business Cards', 'Banners & Billboards', 'Presentation Design', 'Menu Design'],
    whyChoose: [
      { title: 'Fast Turnaround', desc: 'Most designs delivered within 24-48 hours. Rush delivery available.' },
      { title: 'Brand Consistency', desc: 'Every design follows your brand guidelines perfectly.' },
      { title: 'Print + Digital', desc: 'Files are optimized for screen and print, including CMYK and RGB versions.' },
    ],
    faqs: [
      { q: 'How fast can you deliver?', a: 'Standard delivery is 24-48 hours. Rush delivery available for urgent projects.' },
      { q: 'Do you design for print?', a: 'Yes! We deliver print-ready files with proper bleeds, CMYK colors, and high resolution.' },
      { q: 'Can you match my existing brand?', a: 'Absolutely. Send us your brand guidelines and we\'ll match everything perfectly.' },
      { q: 'Do you offer packages for ongoing work?', a: 'Yes! Monthly retainer packages available for consistent content needs.' },
    ],
    portfolio: [
      { name: 'Flavor Fest Campaign', category: 'Social Media Graphics', desc: 'Complete Instagram campaign for food festival', stat: 'Social Media' },
      { name: 'TechCon 2024', category: 'Event Materials', desc: 'Banners, badges, and signage for tech conference', stat: 'Event' },
      { name: 'Bloom Cosmetics', category: 'Product Launch', desc: 'Social media kit for beauty product launch', stat: 'Beauty' },
      { name: 'Urban Eats Menu', category: 'Menu Design', desc: 'Premium restaurant menu and table cards', stat: 'Restaurant' },
      { name: 'StartupPK Pitch', category: 'Presentation Design', desc: 'Investor pitch deck for startup', stat: 'Presentation' },
      { name: 'FitLife Gym', category: 'Marketing Materials', desc: 'Flyers, posters, and social graphics', stat: 'Fitness' },
    ],
  },
  {
    slug: 'shopify-development',
    icon: '♕',
    title: 'Shopify Development',
    short: 'E-commerce storefronts that convert visitors into paying customers.',
    hero: 'Generic Shopify themes cost you revenue. Custom storefronts that match your brand and buying journey convert better.',
    desc: 'Cheap templates are shopping carts charming people buying every competitor uniformly. Your customers recognize when a store genuinely reflects you versus a theme merged with inside pages. We build custom Shopify architectures around your brand story, product collection, and customer psychology — faster loading, easier navigation, segmented ordering information, and checkout friction reduced. Each component exists to increase purchase completion.',
    features: ['Custom Liquid theme development', 'Product page optimization', 'Cart & checkout conversion flow', 'Mobile-first responsive design', 'Speed & performance tuning', 'App integrations (Klaviyo, Recharge, etc)', 'Inventory & collection setup', 'Launch support & QA testing'],
    results: ['+120% avg sales growth', '2.8s avg load time', '95+ mobile speed score'],
    howItWorks: [
      { step: '01', title: 'Discovery & Strategy', desc: 'We analyze your brand, audience, and competitors to create the perfect store blueprint.' },
      { step: '02', title: 'Custom Design', desc: 'Pixel-perfect Figma mockups tailored to your brand identity and conversion goals.' },
      { step: '03', title: 'Liquid Development', desc: 'Clean, modular Shopify Liquid code without bloated themes or unnecessary apps.' },
      { step: '04', title: 'Launch & Optimize', desc: 'Thorough QA testing, speed optimization, and post-launch support.' },
    ],
    categories: ['Fashion & Apparel', 'Skincare & Beauty', 'Food & Supplements', 'Home & Living', 'Jewelry & Accessories', 'Electronics'],
    whyChoose: [
      { title: 'Zero Template Approach', desc: 'Every store is coded from scratch. No Dawn clones. No recycled themes.' },
      { title: 'Conversion Engineering', desc: 'Product pages, cart drawers, and checkout flows designed to maximize AOV and reduce abandonment.' },
      { title: 'Pakistan + International', desc: 'We understand both local PKR markets and international USD/GBP stores.' },
    ],
    faqs: [
      { q: 'Do you use pre-made Shopify themes?', a: 'No. Every theme is custom-coded in Liquid from scratch, tailored to your brand.' },
      { q: 'Can you migrate my store from another platform?', a: 'Yes. We handle migrations from WooCommerce, Magento, BigCommerce, and others with zero data loss.' },
      { q: 'Do you handle Shopify apps and integrations?', a: 'Yes. We integrate Klaviyo, Recharge, Judge.me, and other essential apps for your store.' },
      { q: 'How long does a Shopify store take?', a: 'Typically 3-6 weeks depending on complexity, number of products, and custom features needed.' },
    ],
    portfolio: [
      { name: 'Glamouria', category: 'Fashion & Apparel', desc: 'Premium fashion store with lookbook and quick-buy features', stat: '+120% Sales' },
      { name: 'PureGlow', category: 'Skincare & Beauty', desc: 'Skincare brand with quiz-based product recommendations', stat: '+85% CVR' },
      { name: 'FitFuel', category: 'Health & Supplements', desc: 'Subscription-based supplement store with recurring orders', stat: '+200% Revenue' },
      { name: 'Luxe Jewelry', category: 'Jewelry & Accessories', desc: 'High-end jewelry store with 360° product views', stat: '+150% AOV' },
      { name: 'Home Harmony', category: 'Home & Living', desc: 'Furniture store with room visualization feature', stat: '+90% Traffic' },
      { name: 'TechGear Pro', category: 'Electronics', desc: 'Electronics store with comparison tools', stat: '+75% Sales' },
    ],
  },
  {
    slug: 'website-development',
    icon: '▣',
    title: 'Website Development',
    short: 'Bespoke digital headquarters that establish expertise, simplify discovery, and turn ambush prey hunting ambushers away.',
    hero: 'Outdated portfolio list type pages lose high-value employees. Distinctive modular digital experiences instantly establish position.',
    desc: 'Consumers erase near-instantly when info hunting too much scrolling, intelektul poor visual hierarchy, broken mobile fitting, or anonymous template identity issue. Your value statement gets lost. With thorough competitor and customer mapping, we build complete website framework that communicates leadership style properly. Focus sits on showing what accurate capability means for visitor logistics — booking flow simpler, next-step direction obvious, trust levers visible immediately. Keep clients engaged instead of browsing around corner to leave.',
    features: ['Corporate & business websites', 'Landing pages & funnels', 'Portfolio & personal brand sites', 'SaaS & product websites', 'Real estate & listing sites', 'Restaurant & hospitality sites', 'Educational & course platforms', 'Non-profit & community sites', 'Multi-page custom builds', 'CMS integration (WordPress, headless)'],
    results: ['Sub-2s load time', 'Mobile-first responsive', '100% custom coded'],
    howItWorks: [
      { step: '01', title: 'Requirements Gathering', desc: 'We map out your goals, target audience, and content strategy.' },
      { step: '02', title: 'UI/UX Design', desc: 'Wireframes and high-fidelity mockups in Figma for your approval.' },
      { step: '03', title: 'Development', desc: 'Clean React/Next.js or WordPress build with responsive design.' },
      { step: '04', title: 'Testing & Launch', desc: 'Cross-browser testing, performance audit, and smooth deployment.' },
    ],
    categories: ['Corporate Sites', 'Landing Pages', 'Portfolio Sites', 'SaaS Products', 'Real Estate', 'Restaurants', 'Education', 'Non-Profit'],
    whyChoose: [
      { title: 'Performance First', desc: 'Sub-2-second load times on all devices, including budget smartphones.' },
      { title: 'SEO Built-In', desc: 'Every page is structured for search engines from day one.' },
      { title: 'Custom Everything', desc: 'No WordPress themes. No page builders. Pure custom code.' },
    ],
    faqs: [
      { q: 'What technologies do you use?', a: 'React, Next.js, Vite, Tailwind CSS, WordPress (custom themes), and headless CMS solutions.' },
      { q: 'Can I update content myself?', a: 'Yes. We set up an easy CMS or admin panel so you can update content without a developer.' },
      { q: 'Do you build WordPress sites?', a: 'Yes, but only custom themes. We never use pre-made templates or Elementor.' },
    ],
    portfolio: [
      { name: 'TechNova', category: 'Corporate Website', desc: 'Modern IT solutions company website with case studies', stat: '+64% Leads' },
      { name: 'Decorify', category: 'Portfolio Website', desc: 'Interior design portfolio with gallery and booking', stat: '+90% Traffic' },
      { name: 'MindSpace', category: 'SaaS Website', desc: 'Productivity app landing page with animations', stat: '+45% Signups' },
      { name: 'Elite Properties', category: 'Real Estate', desc: 'Property listing site with advanced filters', stat: '+80% Inquiries' },
      { name: 'Flavor House', category: 'Restaurant', desc: 'Restaurant website with online reservation', stat: '+120% Bookings' },
      { name: 'LearnPro Academy', category: 'Education', desc: 'Online course platform with student dashboard', stat: '+200% Enrollments' },
    ],
  },
  {
    slug: 'custom-theme-development',
    icon: '▣',
    title: 'Custom Theme Development',
    short: 'Proprietary Shopify architecture editable by your in-house staff without developer dependency.',
    hero: 'Theme marketplace solutions cause bloated code, slow performance, and lock-in. Purpose-built themes conform exactly to branded efficiency.',
    desc: 'Most developers offer non-flexible themes disguised as customization. You end paying >$500/year + bloated slow site, full missed ad budget reach. Our storefront source code is hand-written from scratch against your business brief, containing everything needed by tomorrow, with modular sections that non-technical team can reorder or modify through Shopify Settings intuitively. BLAZING quick performance, tiny images WeB formats, clean class-based code ready to compete with international tech-giants without buying premium extension packages.',
    features: ['Zero-dependency Liquid code', 'Modular JSON template sections', 'Shopify admin-friendly editing', 'Brand-specific design system', 'Performance-first architecture', 'Schema markup built-in', 'Cross-browser testing', 'Documentation & handoff'],
    results: ['100% custom code', 'Easy admin editing', 'Future-proof architecture'],
    howItWorks: [
      { step: '01', title: 'Brand Analysis', desc: 'We study your brand guidelines, competitor landscape, and user expectations.' },
      { step: '02', title: 'Section Architecture', desc: 'We plan modular, reusable sections that your team can edit from Shopify admin.' },
      { step: '03', title: 'Clean Liquid Build', desc: 'Hand-coded Liquid with zero bloat, no unnecessary JavaScript, pure performance.' },
      { step: '04', title: 'Documentation', desc: 'Complete handoff with documentation so your team can manage the theme.' },
    ],
    categories: ['Shopify Themes', 'WordPress Themes', 'Custom CMS Themes', 'Headless Themes'],
    whyChoose: [
      { title: 'No Theme Dependencies', desc: 'Your store runs on clean, lightweight code instead of a bloated framework.' },
      { title: 'Admin-Friendly', desc: 'Every section is editable from Shopify admin with clear labels and previews.' },
      { title: 'Scalable Architecture', desc: 'The architecture is built to grow with your brand and makes new sections easier to add.' },
    ],
    faqs: [
      { q: 'What\'s the difference from buying a theme?', a: 'Pre-made themes are generic and bloated. Our themes are purpose-built for your brand with zero unnecessary code.' },
      { q: 'Can my team edit the theme?', a: 'Yes. Every section uses Shopify\'s JSON schema system so non-developers can edit content, images, and layout.' },
      { q: 'Do you provide theme documentation?', a: 'Yes. Complete documentation with screenshots, section guides, and best practices.' },
    ],
    portfolio: [
      { name: 'Artisan Goods', category: 'Handmade Products', desc: 'Custom theme for artisan marketplace', stat: 'Custom Theme' },
      { name: 'Sport Elite', category: 'Sports Equipment', desc: 'High-performance theme with mega menu', stat: 'Custom Theme' },
      { name: 'Organic Life', category: 'Organic Products', desc: 'Clean, minimal theme for health brand', stat: 'Custom Theme' },
    ],
  },
  {
    slug: 'ui-ux-design',
    icon: '✦',
    title: 'UI/UX Design',
    short: 'Interfaces that feel obvious and experiences that make people want to stay and act.',
    hero: 'Difficult navigation sends people to solve-free competitors instead. Clear interfaces retain attention and increase completion.',
    desc: 'Your customers already know how to leave websites faster than open tabs. With user research and behavioral analytics, we design paths so people find value naturally. Usability means converting curiosity into purchase, contact request, sign-up, or subscription without mental stumbling blocks. Every decision simplifies complexity, builds confidence, and creates invisible pressure towards your business goal.',
    features: ['User research & persona mapping', 'Wireframes & interactive prototypes', 'High-fidelity visual design', 'Design system & component library', 'Interaction & micro-animation design', 'Usability testing & iteration', 'Figma deliverables & handoff', 'Responsive design for all devices'],
    results: ['+85% conversion improvement', '4.9/5 client satisfaction', 'Figma-first workflow'],
    howItWorks: [
      { step: '01', title: 'Research & Audit', desc: 'We analyze your current UX, competitors, and user behavior patterns.' },
      { step: '02', title: 'Wireframing', desc: 'Low-fidelity wireframes to map user flows and information architecture.' },
      { step: '03', title: 'Visual Design', desc: 'High-fidelity Figma designs with your brand colors, typography, and imagery.' },
      { step: '04', title: 'Prototype & Test', desc: 'Interactive prototypes tested with real users for feedback and iteration.' },
    ],
    categories: ['Web App Design', 'Mobile App Design', 'E-commerce UX', 'SaaS Dashboard', 'Landing Pages', 'Brand Websites'],
    whyChoose: [
      { title: 'Conversion Psychology', desc: 'Every element is placed with intent and guided by data, not only aesthetics.' },
      { title: 'Figma Mastery', desc: 'Organized Figma files with auto-layout, components, and developer-ready specs.' },
      { title: 'User-Centered', desc: 'We design for your users, not for awards. Beautiful AND functional.' },
    ],
    faqs: [
      { q: 'Do you only design, or also develop?', a: 'We do both. Our design team creates pixel-perfect Figma files, and our dev team builds them.' },
      { q: 'How many design revisions are included?', a: 'Typically 2-3 revision rounds per page. We work closely with you throughout.' },
      { q: 'Can you redesign my existing website?', a: 'Yes. We can audit your current design and create a completely new visual direction.' },
    ],
    portfolio: [
      { name: 'FinTrack App', category: 'Mobile App Design', desc: 'Finance tracking app with dark mode UI', stat: 'App Design' },
      { name: 'CloudSync Dashboard', category: 'SaaS Dashboard', desc: 'Analytics dashboard with data visualization', stat: 'Dashboard' },
      { name: 'ShopEase Mobile', category: 'E-commerce App', desc: 'Mobile shopping experience redesign', stat: 'E-commerce' },
      { name: 'WorkFlow Pro', category: 'Web App Design', desc: 'Project management tool interface', stat: 'Web App' },
    ],
  },
  {
    slug: 'brand-identity',
    icon: '◇',
    title: 'Brand Identity',
    short: 'Complete brand systems that show unique thinking and reliably generate customer confidence.',
    hero: 'Disconnected logos create mixed messages. Unified brand systems that look consistent and purposeful stand out immediately.',
    desc: 'Cheap DIY tools produce random visuals customers interpret as unserious. Your story, values, voice character, colors, and aesthetic patterns form a cohesive identity people intuitively recognize. We figure out who you are, what makes you distinct, then bake everything — packaging, letterhead, admin email signature, service delivery email, social bios — into a system that looks intentionally engineered, not randomly assembled.',
    features: ['Logo design (3 concepts + refinement)', 'Color palette & typography system', 'Brand guidelines document', 'Social media template kit', 'Business card & stationery design', 'Presentation template', 'Brand voice & messaging direction', 'Icon & illustration style'],
    results: ['Complete brand system', 'Print & digital ready', 'Scalable identity'],
    howItWorks: [
      { step: '01', title: 'Brand Discovery', desc: 'Deep dive into your values, audience, competitors, and positioning.' },
      { step: '02', title: 'Concept Development', desc: '3 distinct logo concepts with mood boards and direction.' },
      { step: '03', title: 'Refinement', desc: 'We refine the chosen direction until it\'s perfect.' },
      { step: '04', title: 'Brand Kit Delivery', desc: 'Complete brand guidelines, files, templates, and assets delivered.' },
    ],
    categories: ['Startups', 'E-commerce Brands', 'Service Businesses', 'Personal Brands', 'Restaurants', 'Tech Companies'],
    whyChoose: [
      { title: 'Complete System', desc: 'You receive more than a logo. The full visual identity works across every key touchpoint.' },
      { title: 'Strategy-Led', desc: 'Every design decision is backed by brand positioning and market research.' },
      { title: 'Print + Digital', desc: 'Files ready for web, social media, print, packaging, and signage.' },
    ],
    faqs: [
      { q: 'How many logo concepts do I get?', a: '3 unique concepts with mood boards. You choose one, and we refine it to perfection.' },
      { q: 'Do you design brand guidelines?', a: 'Yes. A comprehensive brand book with logo usage, colors, typography, and visual rules.' },
      { q: 'Can you rebrand my existing business?', a: 'Absolutely. We can evolve your existing identity or create a completely fresh direction.' },
    ],
    portfolio: [
      { name: 'Nova Ventures', category: 'Full Rebrand', desc: 'Complete brand identity for investment firm', stat: 'Rebrand' },
      { name: 'Bloom Beauty', category: 'Beauty Brand', desc: 'Feminine, elegant brand for cosmetics line', stat: 'New Brand' },
      { name: 'Urban Bites', category: 'Restaurant Brand', desc: 'Bold, modern identity for fast-casual chain', stat: 'F&B Brand' },
      { name: 'TechPulse', category: 'Tech Startup', desc: 'Dynamic brand for AI startup', stat: 'Tech Brand' },
    ],
  },
  {
    slug: 'seo',
    icon: '⌕',
    title: 'SEO',
    short: 'Technically sound website platforms that search engines discover, rank, and recommend.',
    hero: 'Invisible online means customers only find competitors. Strategic SEO targets buyers actively searching, not randos accidentally landing.',
    desc: 'Pretty websites mean nothing if potential customers cannot find them when it matters. Slow technical bugs, generic copy, unclear VA page titles stop Google from understanding expertise. We do targeted keyword research based on search intent, technical verification, content architecture, and measurement frameworks — focused on commercial-search queries that bring progresfully customers. Paid ads stop when ad money stops, structured organic traffic sustainability keeps growing long term.',
    features: ['Technical SEO audit & fixes', 'On-page optimization', 'Schema markup (JSON-LD)', 'Page speed optimization', 'Content strategy & keyword research', 'Internal linking structure', 'Google Search Console setup', 'Monthly ranking reports'],
    results: ['+180% organic traffic avg', 'Top 10 rankings', 'Structured data rich results'],
    howItWorks: [
      { step: '01', title: 'SEO Audit', desc: 'Complete technical audit of your current website and search presence.' },
      { step: '02', title: 'Keyword Strategy', desc: 'Research high-intent keywords that your ideal customers are searching.' },
      { step: '03', title: 'On-Page Optimization', desc: 'Optimize every page with proper titles, meta descriptions, headers, and schema.' },
      { step: '04', title: 'Monitor & Improve', desc: 'Monthly reports, ranking tracking, and continuous optimization.' },
    ],
    categories: ['E-commerce SEO', 'Local SEO', 'Technical SEO', 'Content SEO', 'Shopify SEO', 'WordPress SEO'],
    whyChoose: [
      { title: 'Technical Expertise', desc: 'We address Core Web Vitals, schema, crawl issues, and the details many teams overlook.' },
      { title: 'Content Strategy', desc: 'The work goes beyond keywords with a complete plan designed to build topical authority.' },
      { title: 'Transparent Reporting', desc: 'Monthly reports show rankings, traffic, and clear opportunities for improvement.' },
    ],
    faqs: [
      { q: 'How long does SEO take to show results?', a: 'SEO is a long-term strategy. Most clients see improvements in 3-6 months, with significant results by month 6-12.' },
      { q: 'Do you guarantee first page rankings?', a: 'No ethical SEO agency can guarantee rankings. We use proven strategies to improve your visibility consistently.' },
      { q: 'Do you handle content writing?', a: 'Yes. We can create SEO-optimized content, blog posts, and landing page copy.' },
    ],
    portfolio: [
      { name: 'LegalPro Firm', category: 'Local SEO', desc: 'Law firm ranking #1 for city keywords', stat: '+180% Traffic' },
      { name: 'Organic Store', category: 'E-commerce SEO', desc: 'Health store with 50+ ranking keywords', stat: '+220% Organic' },
      { name: 'TechBlog', category: 'Content SEO', desc: 'Tech blog with 100K+ monthly visitors', stat: '+300% Visitors' },
    ],
  },
  {
    slug: 'digital-marketing',
    icon: '↗',
    title: 'Digital Marketing',
    short: 'Customer acquisition strategy combining creative content, psychology-driven campaigns, and measurable results.',
    hero: 'Random content sharing wastes time but strategic campaigns reach buyers actively looking to solve their problem.',
    desc: 'Posting daily without alignment sends potential customers confused signals about what you offer. Thoughtful marketing channels — targeted paid ads, coordinated content feeds, limited-period promos, email nurture — lead customers through logical conversion journey. We create unique campaign narratives that show why specific problem, solution, result matters. Measure everything so investment shows tangible business uplift, not vanity likes.',
    features: ['Social media management', 'Content creation & calendar', 'Campaign strategy & execution', 'Meta & Google ad management', 'Email marketing (Klaviyo)', 'Analytics & performance reporting', 'Audience growth strategy', 'Influencer outreach coordination'],
    results: ['+200% engagement avg', 'Qualified lead generation', 'Full-funnel strategy'],
    howItWorks: [
      { step: '01', title: 'Marketing Audit', desc: 'We analyze your current marketing efforts, channels, and audience.' },
      { step: '02', title: 'Strategy & Calendar', desc: 'A clear content calendar with campaign themes, posts, and ad schedules.' },
      { step: '03', title: 'Execution', desc: 'We create content, manage ads, engage your audience, and optimize.' },
      { step: '04', title: 'Report & Scale', desc: 'Monthly performance reports and strategy adjustments for growth.' },
    ],
    categories: ['Social Media Marketing', 'Paid Advertising', 'Email Marketing', 'Content Marketing', 'Influencer Marketing', 'Growth Hacking'],
    whyChoose: [
      { title: 'Full-Funnel Thinking', desc: 'From awareness through purchase, we build connected systems rather than isolated campaigns.' },
      { title: 'Data-Driven', desc: 'Every decision is backed by analytics, A/B tests, and performance data.' },
      { title: 'Creative + Strategic', desc: 'Beautiful content that\'s also engineered for engagement and conversions.' },
    ],
    faqs: [
      { q: 'Which platforms do you manage?', a: 'Instagram, Facebook, LinkedIn, TikTok, Twitter/X, YouTube, and Google Ads.' },
      { q: 'Do you create the content?', a: 'Yes. Our team handles graphic design, copywriting, video editing, and scheduling.' },
      { q: 'What\'s your minimum engagement period?', a: 'We recommend a minimum of 3 months to see meaningful results from marketing.' },
    ],
    portfolio: [
      { name: 'FashionHub', category: 'Meta Ads', desc: 'Fashion brand with 5x ROAS on ads', stat: '+400% ROAS' },
      { name: 'Fitness First', category: 'Lead Generation', desc: 'Gym chain lead gen campaign', stat: '+150% Leads' },
      { name: 'EduStart', category: 'Content Marketing', desc: 'EdTech content strategy', stat: '+200% Signups' },
    ],
  },
  {
    slug: 'social-media-management',
    icon: '✧',
    title: 'Social Media Management',
    short: 'Long-term social authority and active communities that convert followers into qualified leads and repeat customers.',
    hero: 'Abandoned or mismatched social accounts look neglected. Consistent strategic content grows engagement, trust, and revenue.',
    desc: 'Posting a branded quote once a week is marketing? Does not add business. Competitive differences show actively conversational brands — unique voice, distinctive look-and-feel, authentic thoughts on trends, helpful replies, regular interaction, tailored offerings. Our campaigns match unique customer clusters rather than generic broadcast. Each comment response counts as trust building toward sale. Manual moderation and analytics identify reliable patterns to grow without buying fake followers.',
    features: ['Instagram management & growth', 'Facebook page management', 'LinkedIn content strategy', 'TikTok content direction', 'Content calendar planning', 'Graphic design for posts', 'Caption & hashtag strategy', 'Community management & replies', 'Monthly analytics reporting', 'Reel & story creation'],
    results: ['+200% engagement avg', 'Consistent brand voice', 'Full platform management'],
    howItWorks: [
      { step: '01', title: 'Social Audit', desc: 'We analyze your current profiles, content, and engagement metrics.' },
      { step: '02', title: 'Content Strategy', desc: 'Brand-aligned content pillars, posting schedule, and visual direction.' },
      { step: '03', title: 'Create & Post', desc: 'We design, write, and schedule all content across your platforms.' },
      { step: '04', title: 'Engage & Report', desc: 'Community management, DM responses, and monthly analytics reports.' },
    ],
    categories: ['Instagram', 'Facebook', 'LinkedIn', 'TikTok', 'YouTube', 'Twitter/X'],
    whyChoose: [
      { title: 'Consistent Branding', desc: 'Every post looks and feels aligned with your visual identity and positioning.' },
      { title: 'Engagement Focus', desc: 'We publish, engage, respond, and help build an active community.' },
      { title: 'Full Management', desc: 'We manage the process from strategy and production through publishing and analytics.' },
    ],
    faqs: [
      { q: 'How many posts per week?', a: 'Depends on the package. Typically 3-5 posts per week plus stories and engagement.' },
      { q: 'Do you handle DMs and comments?', a: 'Yes. Community management can include replies to comments and direct messages on your behalf.' },
      { q: 'Can I approve content before posting?', a: 'Absolutely. We share a content calendar for your approval before anything goes live.' },
    ],
    portfolio: [
      { name: 'Cafe Delights', category: 'Instagram Growth', desc: 'Cafe grew from 2K to 25K followers', stat: '+1150% Followers' },
      { name: 'Fashion Nova PK', category: 'Full Management', desc: 'Fashion brand daily content management', stat: '+300% Engagement' },
      { name: 'Tech Reviews', category: 'YouTube Channel', desc: 'Tech channel with consistent uploads', stat: '+50K Subs' },
    ],
  },
  {
    slug: 'speed-optimization',
    icon: '⚡',
    title: 'Speed Optimization',
    short: 'Performance-first website, bi-directional technology stacks, and enhanced user experience retention.',
    hero: 'Slow websites quietly kill qualified leads every minute. Specifically target international and phone-first audiences with aggressive performance tactics.',
    desc: 'Budget phone users and Pakistani data networks experience dynamic barriers. Citizens waiting three seconds already abandoning your site, messages, or next step. Professional recommended techniques can compress without portoflio image quality compromise, shrink JavaScript execution costs, fine-tune caching patterns used by Vercel and global edge services, and recalibrate genuine mobile experience. Deliverability does matter equally to design quality.',
    features: ['Image compression & WebP conversion', 'JavaScript bundle optimization', 'CSS & font optimization', 'Third-party script audit', 'Lazy loading implementation', 'CDN configuration', 'Core Web Vitals improvement', 'Server response optimization'],
    results: ['Sub-2s load time', '95+ PageSpeed score', '40% bounce rate reduction'],
    howItWorks: [
      { step: '01', title: 'Speed Audit', desc: 'We test your site on real devices and identify every bottleneck.' },
      { step: '02', title: 'Asset Optimization', desc: 'Compress images, optimize fonts, and reduce JavaScript payload.' },
      { step: '03', title: 'Code Optimization', desc: 'Remove unused CSS/JS, implement lazy loading, and optimize rendering.' },
      { step: '04', title: 'Testing & Monitoring', desc: 'Verify improvements on real devices and set up monitoring.' },
    ],
    categories: ['Shopify Speed', 'WordPress Speed', 'React/Next.js Speed', 'Core Web Vitals', 'Mobile Performance', 'Image Optimization'],
    whyChoose: [
      { title: 'Real Device Testing', desc: 'We test on actual budget phones as well as browser-based simulations.' },
      { title: 'Pakistan-Focused', desc: 'We optimize for 3G/4G networks and low-end Android devices common in Pakistan.' },
      { title: 'Measurable Results', desc: 'Before/after reports with PageSpeed scores, load times, and Core Web Vitals.' },
    ],
    faqs: [
      { q: 'How much faster can my site get?', a: 'Most sites see 40-70% improvement in load times after our optimization.' },
      { q: 'Will optimization break anything?', a: 'No. We test thoroughly and make changes incrementally. Nothing breaks.' },
      { q: 'Do you optimize Shopify stores?', a: 'Yes. Shopify speed optimization can cover images, apps, scripts, and Liquid code.' },
    ],
    portfolio: [
      { name: 'SlowStore Fix', category: 'Shopify Speed', desc: 'Shopify store from 6s to 1.8s load time', stat: '70% Faster' },
      { name: 'WordPress Rescue', category: 'WordPress Speed', desc: 'Blog from 8s to 2s with caching', stat: '75% Faster' },
      { name: 'React App Boost', category: 'Web App Speed', desc: 'SaaS app bundle size reduced 60%', stat: '60% Smaller' },
    ],
  },
  {
    slug: 'maintenance-support',
    icon: '🛡',
    title: 'Maintenance & Support',
    short: 'Ongoing updates, security, and optimization so you never fall behind.',
    hero: 'Your website deserves continuous care, not only a one-time build.',
    desc: 'A website is not a one-time project. It needs ongoing care. Our monthly maintenance options keep your site updated, secure, fast, and optimized. We handle bug fixes, content updates, security patches, and performance monitoring so your team can focus on the business.',
    features: ['Monthly updates & patches', 'Security monitoring & fixes', 'Performance optimization', 'Content updates & changes', 'Bug fixes & troubleshooting', 'Uptime monitoring', 'Monthly health reports', 'Priority support channel'],
    results: ['99.9% uptime', '24hr response time', 'Zero security incidents'],
    howItWorks: [
      { step: '01', title: 'Onboarding', desc: 'We audit your current site and set up monitoring systems.' },
      { step: '02', title: 'Monthly Maintenance', desc: 'Regular updates, security patches, and performance checks.' },
      { step: '03', title: 'Content Updates', desc: 'We handle your content changes, new pages, and design tweaks.' },
      { step: '04', title: 'Monthly Report', desc: 'Detailed report on uptime, speed, security, and changes made.' },
    ],
    categories: ['Shopify Maintenance', 'WordPress Maintenance', 'Custom Site Maintenance', 'Security Monitoring', 'Performance Monitoring'],
    whyChoose: [
      { title: 'Proactive Care', desc: 'We monitor the experience and address risks before they become larger problems.' },
      { title: 'Priority Support', desc: 'A direct WhatsApp channel is available for urgent issues, with response based on the support plan.' },
      { title: 'Transparent Reports', desc: 'Monthly reports showing exactly what we did, what changed, and what\'s next.' },
    ],
    faqs: [
      { q: 'What does maintenance include?', a: 'Updates, security patches, bug fixes, content changes, speed checks, and monthly reports.' },
      { q: 'How quickly do you respond to issues?', a: 'Urgent issues within 2-4 hours. Regular requests within 24 hours.' },
      { q: 'Can I cancel the maintenance plan?', a: 'Yes. No long-term lock-in. Cancel anytime with 30 days notice.' },
    ],
    portfolio: [
      { name: 'E-commerce Store', category: 'Ongoing Support', desc: '2+ years of continuous maintenance', stat: '99.9% Uptime' },
      { name: 'Corporate Site', category: 'Security + Updates', desc: 'Monthly security patches and backups', stat: '0 Incidents' },
      { name: 'SaaS Platform', category: 'Performance', desc: 'Continuous optimization and monitoring', stat: '24/7 Support' },
    ],
  },
].sort((a, b) => servicePriority.indexOf(a.slug) - servicePriority.indexOf(b.slug));
